### PR TITLE
Legend controls

### PR DESCRIPTION
**Pull request by akacarlyann**
Work in progress!

- [x] adds legend parameter to MapViz to control legend visibility (defaults to True for all viz classes except HeatmapViz, RasterTilesViz and ImageViz)
- [x] moves legend div creation to JS
- [x] refine CSS style for default legend
- [x] horizontal legend style
- [x] continuous gradient legend
- [ ] variable radius legend

May leave these for map-collections pr:  
- [ ] multi-layer legends 
- [ ] multi-variable legends

### CODE REVIEW

**Comment by akacarlyann** [comment]
The new Mapbox attribution icon takes up a ton of room, which makes the legend look out of place.  Looking for suggestions on how to rearrange legend and other map info/controls!

screen shot 2018-05-05 at 5 45 45 pm

**Comment by ryanbaumann** [comment]
Nice, that legend design looks great @akacarlyann!  Huge improvement.  🙏 

> Looking for suggestions on how to rearrange legend and other map info/controls!

Lots of options here - what about putting both the attribution and legend at the bottom of the map, and move the attribution icon to the left of the legend?

**Comment by akacarlyann** [comment]
Thought heatmaps could benefit from a continuous legend titled using __weight_property__ .  Implementation is clunky atm and assumes evenly spaced colors/stops. screen shot 2018-05-06 at 1 26 07 am

**Comment by ryanbaumann** [comment]
Looks good as a starting point @akacarlyann.

  The hard part with Heatmaps is that the color is not a perfect representation of the values specified in the legend, since the kernel density calculation sums up all values in the specified heatmap-radius region to calculate the color.  

We could solve that by clustering & aggregating the underlying data, and choosing a heatmap-radius to match the cluster-radius, so that the kernel density calculation is close to an exact representation of the color shown on the screen.

**Comment by akacarlyann** [comment]
@ryanbaumann Got it. I think I'll roll back the heatmap legend for now and leave that for someone's future PR since it will be more involved. I'll try to get the variable-radius legend in this week and I'll let you know when it's ready for review!

**Comment by ryanbaumann** [comment]
No rush - we'll have more bandwidth here starting next week too.

**Comment by ryanbaumann** [comment]
@akacarlyann the latest changes look great!  Are you ready for a review?

**Comment by akacarlyann** [comment]
@ryanbaumann Really close! I have a couple moving parts - setting a default shape for legend keys in each viz type and supporting circular legend keys in the horizontal layout. Happy to take any comments now but I should have those last pieces done by Wed, I think!

**Comment by akacarlyann** [comment]
@ryanbaumann Ready for a review on this :)

**Comment by akacarlyann** [comment]
🎉

**Pull request merged**
