### PR TITLE
add python2.7 to travis matrix

### PR DESCRIPTION
**Pull request by vincentsarago**
☝️

### CODE REVIEW

**Comment by vincentsarago** [comment]
python 2.7 tests passes 🎉 

### Note: 
python2 and 3.6 test take ~1min40 while tests for python 3.4 it takes 8-9min. I wonder why and if we really have to tests python3.4. 

e.g on rasterio we only run tests for python 2.7 and 3.6 
cc @perrygeo @ryanbaumann

**Comment by ryanbaumann** [comment]
@vincentsarago I'm 👍 on removing the test for Python 3.4 and only doing 2.7 and 3.6.  cc @perrygeo for final 👀

**Comment by perrygeo** [comment]
No reason to test on python 3.4 - if it works on 2.7 & 3.6, it should work on everything in between.

**Comment by ryanbaumann** [comment]
Nice!  @vincentsarago let's remove Python 3.4 and merge this PR.

**Pull request merged**
