### PR TITLE
Export map to image

### LINKED ISSUE #2: Add image export function to viz classes
A common data science workflow is to include a static image version of a visual for sharing or screen shot creating.  

This could be added as a `saveImage()` HTML button on a `viz` class object that downloads the current map viewport as a PNG, or it could be a viz.toImage() python function that outputs a PNG of the viz at the stated zoom, center, pitch, and bearing.

### PR DESCRIPTION
**Pull request by akacarlyann**
Use `MapViz` parameter `add_snapshot_links=True` to add download buttons to map cell in Jupyter notebook.  Mapbox's map canvas includes only the map image, so we'll have to figure out a way to composite the legend canvas and map canvas that I've currently pulled out.  Here's a start for #2 though.

Closes #2.

### CODE REVIEW

**Comment by akacarlyann** [comment]
@ryanbaumann When you get a chance, it would be great to get some feedback on this PR.  Image export is fairly simple if we don't need to preserve the legend.  I'm also looking into abstracting the download buttons into a separate widget.

**Comment by akacarlyann** [comment]
@ryanbaumann Updated to keep `preserveDrawingBuffer` as false unless map screencapture is enabled.  

Usage example (for an existing viz):
```viz.add_snapshot_links = True```
map screen capture example

**Comment by ryanbaumann** [comment]
This looks great @akacarlyann.  Ready to merge?

**Comment by akacarlyann** [comment]
@ryanbaumann Yup. All set.

**Pull request merged**
