### PR TITLE
Fixed broken Mapbox logo link in Readme

### PR DESCRIPTION
**Pull request by pratikyadav**

### CODE REVIEW

**Comment by akacarlyann** [comment]
Thanks! But this is a duplicate of #166.

**Comment by pratikyadav** [comment]
@akacarlyann Thanks for pointing it out. :)

Yes, it is a duplicate but https://github.com/mapbox/mapboxgl-jupyter/pull/166 was out of date with the master branch to merge which I saw after opening this PR.

**Comment by akacarlyann** [comment]
@pratikyadav Ah I see. The maintainer can merge master into the dev branch on #166 to bring it up to date. Are you referencing the same logo file?

**Comment by pratikyadav** [comment]
> Are you referencing the same logo file?

No, not exactly the same in terms of dimension.

**Pull request closed without merging**
