### PR TITLE
update example data url structure

### PR DESCRIPTION
**Pull request by ryanbaumann**
* Fix all examples to use Git URL links to data

### CODE REVIEW

**Comment by anmolgarg** [comment]
FYI, your mapbox access token is sitting in plain text in the notebooks when not rendered. I would clear all output before pushing.

**Comment by ryanbaumann** [comment]
Thanks, @anmolgarg.  It's a public token, so it has read-only access to all APIs.

We will clear out the token out from the examples, out and rotate the token in the examples today.

**Comment by anmolgarg** [comment]
Cool. It gave me a chance to check out the zip code viz which does not work under my account since I believe I don't have access to `mapbox://rsbaumann.bv2k1pl2`.

**Comment by ryanbaumann** [comment]
@anmolgarg I just made that tileset (`mapbox://rsbaumann.bv2k1pl2`) public - let me know if the postcode example works now!

**Comment by anmolgarg** [comment]
Hm nope, still not working for me.

**Comment by ryanbaumann** [comment]
@anmolgarg you may have to clear your browser cache to try it out immediately - I just confirmed the tileset is public and I can retrieve it with any Mapbox public access token.

**Comment by anmolgarg** [comment]
That did the trick. Confirmed its working now. Awesome stuff!

**Comment by ryanbaumann** [comment]
Will get some more examples moving soon @anmolgarg.  It works with any tileset you put on your Mapbox account.  Stay tuned, and share what you build!

**Pull request merged**
