### PR TITLE
Map control scale bar

### LINKED ISSUE #143: Adding a scale in mapboxgl-jupyter
Hello again

I noticed that there is no possibility to add a scale on the map (Jupyter Notebook, Python 3).

It seems that this possibility exists in the JS version (it was pointed to me by your helpdesk).
See screenshot below.

Would it be possible to also have this feature added in the maboxgl-jupyter?

Cheers :-)
mapbox_js_scale

### PR DESCRIPTION
**Pull request by akacarlyann**
Optionally add a map control scale bar to any MapViz with custom position and styling.  Closes #143.

Usage example: 
```
import os
from mapboxgl.viz import *

# Create the viz from the dataframe
viz = CircleViz('../data/healthcare_points.geojson',
                access_token=os.getenv('MAPBOX_ACCESS_TOKEN'), 
                center=(-95, 40),
                zoom=2.5,
                scale=True,
                scale_unit_system='imperial',
                scale_position='top-left',
                scale_border_color='#6e6e6e', 
                scale_background_color='#eee',
                scale_text_color='#131516')

# Show the viz
viz.show()
```
scale bar

### CODE REVIEW

**Comment by akacarlyann** [comment]
Sure thing! I had added one example to https://github.com/akacarlyann/mapboxgl-jupyter/blob/map-scale/examples/notebooks/scale-annotation.ipynb before opening the PR. @ryanbaumann Which notebook should I integrate this into?

**Comment by ryanbaumann** [comment]
I'd recommend adding to https://github.com/mapbox/mapboxgl-jupyter/blob/master/examples/notebooks/point-viz-types-example.ipynb

**Comment by akacarlyann** [comment]
@ryanbaumann sounds good.  Added in 57f9014.

**Comment by ryanbaumann** [comment]
Looks good - ready to merge if you are @akacarlyann

**Comment by akacarlyann** [comment]
@ryanbaumann It's ready!

**Pull request merged**
