### PR TITLE
Variable radius legend

### PR DESCRIPTION
**Pull request by akacarlyann**
Adds support for a variable radius legend for the GraduatedCircleViz. Adds legend_function parameter for selecting between calcColorLegend and calcRadiusLegend in JavaScript. Addresses #80.

### CODE REVIEW

**Comment by akacarlyann** [comment]
@ryanbaumann No multi-dimensional legends just yet, so the variable radius is using the `color_default` parameter.  Here's a screen-cap of the example in the legend-controls notebook.  Both horizontal and vertical legend layouts are supported, but the spacing between the legend items is contingent on the diameter of the largest legend item key.
variable_radius_legend

**Comment by ryanbaumann** [comment]
Great.  I'd anticipate that a user would expect **both** color and size options for a GraduatedCircleMap - I lean towards not merging this until we can incorporate both size and color into the legend.

**Comment by akacarlyann** [comment]
@ryanbaumann Makes sense to me to.  Before this point only color legends were available for graduated circle visualizations.  I think adding multiple sub-legends could parallel the multi-layer visualizations so I had expected that support to be wrapped in #129 but I'm happy to scratch out some ideas for this.

**Comment by ryanbaumann** [comment]
Yep, that looks great.  I agree that legend real-estate is hard to manage - collapsable seems like a good option.

**Comment by ryanbaumann** [comment]
Should I plan to merge this PR in, with a followup PR for collapsing the legends @akacarlyann ?

**Comment by akacarlyann** [comment]
@ryanbaumann I think I have a few commits locally to support the double graduated circle legend so I need to push those first.

**Comment by akacarlyann** [comment]
@ryanbaumann I added a couple functions to better automatically place a secondary legend, as in the case with the graduated circle default.  I'm ready for review/merge when you are :)

**Comment by caerus-data** [comment]
Still not seeing this functionality on GraduatedCircleViz, despite legends being displayed in the examples. Will this Merge resolve?

**Comment by akacarlyann** [comment]
@caerus-data it's ready for merge as of last week :) Glad it will be useful!  @ryanbaumann the coveralls test looks like it stalled but I would hope this PR doesn't decrease coverage.

**Comment by caerus-data** [comment]
Sorry - to be more clear - I've created a viz object based on the examples

`viz.legend`
>True

but `viz.show()` 
yields a map with no Legend.

Windows 10, attempted in both Py36 and 27

I'm getting warnings about IFrame, but am not sure how to convert my dataframe to html_data - perhaps that's the culprit?

**Comment by caerus-data** [comment]
Tightened up my issue. Will post as a new question

**Pull request merged**
