### PR TITLE
Add 3-d option for choropleth extrusion; support pitch and bearing arguments for MapViz

### LINKED ISSUE #83: Add 3D `height` option to ChoroplethViz
Add support to `extrude` a Choropleth polygon layer.  Expose the option as `height*` properties to the Choropleth Viz.  

* `height_stops`
* `height_property`
* `height_default`

Example Viz: 3D Population Density - www.mapbox.com/bites/00273

### PR DESCRIPTION
**Pull request by akacarlyann**
Addresses #4, #15; closes #83

### CODE REVIEW

**Comment by ryanbaumann** [comment]
Hehe, this is awesome @akacarlyann.  Nice work!



Notes:

- Tooltips: if the same measure is used for both height and color, do not put the same property in the tooltip twice.
- Legend: if a different measure is used for color and height, we should mention the measure in the legend and indicate what color vs. height represents.

**Comment by ryanbaumann** [comment]
@akacarlyann no rush here yet, but wondering if you've had a chance for to take a pass on any of the feedback above or are ready for a final PR review.

**Comment by akacarlyann** [comment]
@ryanbaumann funny timing - I'm heading to the coffee shop to work on this today! It's my first chance in a couple weeks. For the SF population graphic, there is an updating scale 3d height in the legend. Is there any public source code you can think of that might implement something similar? Otherwise I'll just handle it similarly to the way we do color v radius for the graduated circle viz.

**Comment by ryanbaumann** [comment]
@akacarlyann the legend in www.mapbox.com/bites/00273 is pretty custom CSS and HTML - I'd have to search around to see if there are any modularized components for size extruded / 3D data visualizations

**Comment by akacarlyann** [comment]
@ryanbaumann Got it.  Removed duplicate add to tooltip if __height_property__ equals __color_property__ and added note to legend title if height based on different property from color.  Ready for you to take a look.

**Comment by ryanbaumann** [comment]
Nice work @akacarlyann.  A few updates to tests for coverage of the new utils function `height_map` and I think we're ready to merge.

**Comment by ryanbaumann** [comment]
Thanks @lucasvw - could you open a quick issue ticket or PR for the change or bug?  This PR is old.  Thank you!

**Pull request merged**
