### PR TITLE
Add support for easily converting GeoPandas objects to geojson

### PR DESCRIPTION
**Pull request by zoharby**
Really handy for Polygon visualizations which can be created with a single line from a GeoPandas GeoDataFrame

What I did (feel free to comment, it's not a finely polished solution):

- Changed df_to_geojson into a generic _to_geojson
- Added df_to_geojson and gdf_to_geojson wrappers

### CODE REVIEW

**Comment by zoharby** [comment]
Oh, didn't realize the contributing guidelines state I should create a new branch. Hope this doesn't make a mess. If needed I can close and re-create...

**Comment by ryanbaumann** [comment]
@zoharby thanks for the PR!

Would this simpler solution work well for your use case?  https://github.com/mapbox/mapboxgl-jupyter/issues/66#issuecomment-377607459

I think we could just perform this `is_gf_a_geodataframe` check on the `df` variable passed to the `df_to_geojson` function.  If it is, use the logic in the comment above to convert the geodataframe to geojson.  If the `filename` option is present, save the output to a file.  Otherwise, return the geojson-format python dictionary.

**Comment by zoharby** [comment]
Right, I completely missed this much simpler solution...
Will try to make a new PR based on this approach

**Comment by zoharby** [comment]
Issued a new PR #122 based on the mentioned solution. Closing this one.

**Pull request closed without merging**
