### PR TITLE
Abstract common Viz properties to MapViz base class; add base.html map template

### PR DESCRIPTION
**Pull request by akacarlyann**
CircleViz, GraduatedCircleViz, HeatmapViz, and ClusteredCircleViz now inherit from MapViz base class in viz.py; addresses #6

### CODE REVIEW

**Comment by akacarlyann** [comment]
This could be extended to by moving the create_html() method to MapViz only; it would then need to take unique template variables as an argument.  Any thoughts on this?

**Comment by ryanbaumann** [comment]
Nice refactoring @akacarlyann !  I agree on moving the `create_html()` method to the MapViz object, accepting only unique template parameters.  Then there is no code duplication among viz types, and creating a new viz type should be really straightforward.   

Can you add this to your PR?  Rest looks great.

**Comment by akacarlyann** [comment]
@ryanbaumann  Sure thing!  I added a method "add_unique_template_variables" to each class to account for this.  I'm not attached to the name, if you think something else might better match the MapboxGL style.

MapViz example:
```
map = MapViz(data, access_token=token, height='400px', center=(-121, 37.5), zoom=4.5)
map.show()
```
will generate a generic map (no legend) from the template __base.html__ with black points (circles of radius 1) at the specified center/zoom levels.

**Comment by ryanbaumann** [comment]
Beautiful.  Impressive code simplification @akacarlyann 🙏 .

**Comment by akacarlyann** [comment]
Aw shucks.  Happy to help!

**Pull request merged**
